export const drillConeConfig = {
  // Level 1
  TRIPLE_CONE_DRILL: { expected: 3, min: 3, max: 3 },
  "7_CONE_WEAVE": { expected: 7, min: 7, max: 7 },
  ZIGZAG_DRILL: { expected: 5, min: 5, max: 6 },
  PASSING_RECEIVING_TURNING: null,
  KEEPY_UPPIES: null,
  // Level 2
  FIGURE_OF_8_DRILL: { expected: 5, min: 5, max: 5 },
  DIAMOND_DRIBBLING: { expected: 5, min: 5, max: 5 },
  DRIBBLE_PASS_DRIBBLE: { expected: 8, min: 8, max: 8 },
  THREE_GATE_PASS: { expected: 6, min: 6, max: 6 },
  KEEPY_UPPIES_SECOND: null,
  // Level 3
  DRIBBLE_ZIGZAG_DRIBBLE: { expected: 11, min: 11, max: 12 },
  CHEST_CONTROL_DRIBBLE: { expected: 6, min: 6, max: 6 },
  CHEST_CONTROL_WEAVE: null,
  THREE_GATE_PASS_DRIBBLE: { expected: 9, min: 9, max: 9 },
  KEEPY_UPPIES_THIRD: null,
  // Level 4
  FIVE_CONE_DRILL: { expected: 5, min: 5, max: 5 },
  "7_CONE_WEAVE_SECOND": { expected: 7, min: 7, max: 7 },
  DIAMOND_DRIBBLING_SECOND: { expected: 5, min: 5, max: 5 },
  PASSING_RECEIVING_TURNING_SHUTTLE: null,
  KEEPY_UPPIES_FOURTH: null,
  // Level 5
  THREE_GATE_PASS_SECOND: { expected: 6, min: 6, max: 6 },
  PASSING_RECEIVING_TURNING_MIXED_COMBO: null,
  PASSING_RECEIVING_TURNING_WEAVE: null,
  DIAMOND_SHUTTLE_DRILL: null,
  KEEPY_UPPIES_FIFTH: null,

  // Label aliases (for when gameType is stored as label instead of value)
  "Triple Cone Drill": { expected: 3, min: 3, max: 3 },
  "7 Cone Weave": { expected: 7, min: 7, max: 7 },
  "Zigzag Drill": { expected: 5, min: 5, max: 6 },
  "Passing Receiving Turning": null,
  "Keepy Uppies": null,
  "Figure of 8 Drill": { expected: 5, min: 5, max: 5 },
  "Diamond Dribbling": { expected: 5, min: 5, max: 5 },
  "Dribble Pass Dribble": { expected: 8, min: 8, max: 8 },
  "Three Gate Pass": { expected: 6, min: 6, max: 6 },
  "Dribble Zigzag Dribble": { expected: 11, min: 11, max: 12 },
  "Chest Control Dribble": { expected: 6, min: 6, max: 6 },
  "Three Gate Pass Dribble": { expected: 9, min: 9, max: 9 },
  "Five Cone Drill": { expected: 5, min: 5, max: 5 },
  "7 Cone Weave Second": { expected: 7, min: 7, max: 7 },
  "Diamond Dribbling Second": { expected: 5, min: 5, max: 5 },
  "Three Gate Pass Second": { expected: 6, min: 6, max: 6 },
};

// Dropdown options for drill type selector
export const drillTypeOptions = [
  { value: 'TRIPLE_CONE_DRILL', label: 'Triple Cone Drill', expectedCones: '3' },
  { value: '7_CONE_WEAVE', label: '7 Cone Weave', expectedCones: '7' },
  { value: 'ZIGZAG_DRILL', label: 'Zigzag Drill', expectedCones: '5-6' },
  { value: 'FIGURE_OF_8_DRILL', label: 'Figure of 8 Drill', expectedCones: '5' },
  { value: 'DIAMOND_DRIBBLING', label: 'Diamond Dribbling', expectedCones: '5' },
  { value: 'DRIBBLE_PASS_DRIBBLE', label: 'Dribble Pass Dribble', expectedCones: '8' },
  { value: 'THREE_GATE_PASS', label: 'Three Gate Pass', expectedCones: '6' },
  { value: 'DRIBBLE_ZIGZAG_DRIBBLE', label: 'Dribble Zigzag Dribble', expectedCones: '11-12' },
  { value: 'CHEST_CONTROL_DRIBBLE', label: 'Chest Control Dribble', expectedCones: '6' },
  { value: 'THREE_GATE_PASS_DRIBBLE', label: 'Three Gate Pass Dribble', expectedCones: '9' },
  { value: 'FIVE_CONE_DRILL', label: 'Five Cone Drill', expectedCones: '5' },
  { value: '7_CONE_WEAVE_SECOND', label: '7 Cone Weave Second', expectedCones: '7' },
  { value: 'DIAMOND_DRIBBLING_SECOND', label: 'Diamond Dribbling Second', expectedCones: '5' },
  { value: 'THREE_GATE_PASS_SECOND', label: 'Three Gate Pass Second', expectedCones: '6' },
  { value: 'PASSING_RECEIVING_TURNING', label: 'Passing Receiving Turning', expectedCones: null },
  { value: 'PASSING_RECEIVING_TURNING_SHUTTLE', label: 'Passing Receiving Turning Shuttle', expectedCones: null },
  { value: 'PASSING_RECEIVING_TURNING_MIXED_COMBO', label: 'Passing Receiving Turning Mixed Combo', expectedCones: null },
  { value: 'PASSING_RECEIVING_TURNING_WEAVE', label: 'Passing Receiving Turning Weave', expectedCones: null },
  { value: 'DIAMOND_SHUTTLE_DRILL', label: 'Diamond Shuttle Drill', expectedCones: null },
  { value: 'KEEPY_UPPIES', label: 'Keepy Uppies', expectedCones: null },
];
